### ISSUE TITLE
NumericStepper improvements

### ISSUE THREAD

**Issue by vepanimas** [devex-web-frontend/dx-components#9]
1. We should improve `formatter` passed to the component. **Numeric stepper** should have an ability to display value as a custom string, for example, display a timestamp in ms as custom date string.
2. We should have an ability to disable value manual editing. It could be a prop `manualEdit: bool` with default `True` value.
3. Provide additional `onClick` handler to input. We may need it when this component will be used in composition to create another high-order component (for example, DatePicker should be shown when user clicked on the numeric stepper).

**Comment by raveclassic** [comment]
Some remarks:
1. This should be possible by passing custom Input class to props (research DI)
2. This is related to purely controlled behavior, maybe we should accept current input string as props
3. We'd better investigate `onFocus`/`onBlur` rather than `onClick`

**Comment by mankdev** [comment]
als we should properly handle floats, now we have following bug:
STR: 
set value to 0.25
step to 0.01
click increase 5 times

actual result:
value changes to 0.30000000000000004

may be we should provide *formatter* prop by component interface?

**Comment by raveclassic** [comment]
Considering handling floats maybe a formatter function would be better than custom Input component.

**Comment by raveclassic** [comment]
Investigate `stateful` for controlled/uncontrolled behavior.
Sometimes NS does not show new `value` from props.

**Comment by raveclassic** [comment]
Regarding floats - all operations with floats should be done in precision which should be inferred from number of digits after dot in `step` value

**Comment by raveclassic** [comment]
New component `NumberInput` should be implemented under this ticked for the sake of compatibility because there'll a lot of breaking changes if we try to update existing `NumericStepper`.

**Comment by raveclassic** [comment]
Even more, customizable increment/decrement logic will be done under another task - `TimeInput`
